version: '3.9'

services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info --concurrency=1 -Q otp_queue
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis